RACES:
  human:
    name:
      ru: человек

    description: | 
      Встречающиеся по всей мультивселенной, люди столь же разнообразны, сколь многочисленны, и они стремятся достичь
      как можно большего за отведенные им годы. Их амбиции и изобретательность вызывают восхищение, уважение и страх во
      многих мирах.Люди разнообразны внешне, как и жители Земли, и у них множество богов. Ученые спорят о происхождении 
      человечества, но одно из самых ранних известных скоплений людей, как говорят, произошло в Сигиле — торообразном 
      городе в центре мультивселенной, месте, где родился Общий язык. Оттуда люди могли распространиться по всем уголкам
      мультивселенной, неся с собой космополитизм Города Дверей.
      

    creature_type:
      type: humanoid
      name:
        ru: гуманоид

    size:
      value: medium
      name:
        ru: средний

    speed: 30

    race_ability:
      resourcefulness:
        name:
          ru: находчивость
        description: Вы получаете Героическое вдохновение каждый раз после продолжительного отдыха

      skilled:
        name:
          ru: умелость
        description: Вы получаете владение одним навыком на ваш выбор.

      universality:
        name:
          ru: универсальность
        description: Вы получаете черту Происхождения на ваш выбор. (рекомендуется выбрать черту Одарённый)

  orc:
    name:
      ru: орк

    description: |
      Орки связывают свое происхождение с Груумшем, могущественным богом, который бродил побескрайним просторам 
      Материального Плана. Груумш наделил своих детей дарами, чтобы они могли путешествовать по огромным равнинам,
      обширным пещерам и бурным морям и проти-востоять монстрам, скрывающимся там. Дажекогда орки начинают поклонятся 
      другим богам,они сохраняют дары Груумша: выносливость, решимость и способность видеть в темноте. В среднем орки 
      высокие и широкоплечие. У них серая кожа, заостренные уши и выдающиеся нижние клыки, похожие на маленькие бивни. 
      Молодым оркам в некоторых мирах рассказывают истории о великих путешествиях и испытаниях их предков. 
      Вдохновленные этими историями,многие орки задаются вопросом, когда Груумш призовет их совершить героические 
      подвиги древности и окажутся ли они достойны его благо-склонности. Другие орки предпочитают оставить старые 
      истории в прошлом и найти свой собственный путь.

    creature_type:
      type: humanoid
      name:
        ru: гуманоид

    size:
      value: medium
      name:
        ru: средний
    speed: 30

    race_ability:
      adrenaline_rush:
        name:
          ru: всплеск адреналина
        description: |
          Вы можете совершить Бонусным Действием действие Рывок. Когда вы это делаете, вы получаете временные хиты в 
          количестве, равном вашему бонусу мастерства. Вы можете использовать это умение количество раз, равное вашему
          бонусу мастерства, и восстанавливаете все потраченные использования после Короткого или Продолжительного Отдыха.

      dark_vision:
          value: 120
          name:
            ru: тёмное зрение
          description: У вас есть тёмное зрение в пределах 120 футов

      unwavering_fortitude:
        name:
          ru: непоколибимая стойкость
        description: |
          Если ваши хиты опустились до нуля, но вы при этом не убиты, ваши хиты вместо этого опускаются до 1. Вы не 
          можете использовать эту способность снова, пока отдых не завершите продолжительный отдых.



  elf:
    name:
      ru: эльф

    description: |
      Созданные богом Кореллоном, первые эльфы могли менять свои формы по своему желанию. Они утратили эту способность, 
      когда Кореллон проклял их за сговор с божеством Лолс, которая пыталась, но не смогла узурпировать власть Кореллона. 
      Когда Лолс была низвергнута в Бездну, большинство эльфов отвергли её и заслужили прощение Кореллона, но то, что 
      Кореллон у них отнял, было утрачено навсегда. Потеряв способность изменять форму по своему желанию, эльфы 
      отступили в Страну Фей, где их печаль только усилилась под влиянием этого плана. Со временем любопытство привело 
      многих из них к исследованию других измерений, включая миры Материального Плана. Эльфы обладают заостренными ушами 
      и не имеют растительности на лице и теле. Они живут около 750 лет и не спят, а вместо этого входят в транс, когда 
      нуждаются в отдыхе. В этом состоянии они остаются осведомлёнными о своём окружении, погружаясь в воспоминания и 
      медитации. Окружающая среда постепенно трансформирует эльфов, если они живут в ней более тысячи лет, и наделяет их 
      определённой магией. Дроу,высшие эльфы и лесные эльфы — примеры эльфов, подвергшихся таким изменениям.


    creature_type:
      type: humanoid
      name:
        ru: гуманоид

    size:
      value: medium
      name:
        ru: средний
    speed: 30

    race_ability:
      dark_vision:
        value: 60
        name:
          ru: тёмное зрение
        description: У вас есть тёмное зрение в пределах 60 футов

      elven_origin:
        name:
          ru: эльфийское происходение
        description: |
          Вы принадлежите к родословной, которая наделяет вас сверхъестественными способностями. Выберите происхождение 
          из таблицы эльфийских происхождений. Интеллект, Мудрость или Харизма является вашей заклинательной 
          характеристикой для заклинаний, которые вы используете с помощью этой особенности (выберите характеристику при
          выборе родословной).

      legacy_of_fae:
        name:
          ru: наследие фей
        description: |
          Вы получаете Преимущество на спасброски, которые совершаете, чтобы избежать или прекратить состояние Очарованый

      heightened_senses:
        name:
          ru: обострённые чувства
        description: |
          Вы получаете владение одним навыком на выбор из списка: Проницательность, Внимательность или Выживание.

      trance:
        name:
          ru: транс
        description: |
          Вам не нужно спать, и магия не может вас усыпить. Вы можете завершить продолжительный отдых за 4 часа, если 
          проводите эти часы в состоянии транса, во время которого сохраняете сознание.
    sub_races:
      high_elf:
        name:
          ru: высший эльф
        description: |
          Высшие эльфы пропитаны магией пересечения между Страной Фей и Материальным Планом. В некоторых мирах высшие 
          эльфы называют себя другими именами. Например, в сеттинге Забытых Королевств они называют себя солнечными
          или лунными эльфами, в сеттинге Драконье копьё — Сильванести и Квалинести, а в сеттинге Эберрон — Аэрени.

        first_lvl: |
          Вы знаете заговор Фокусы. Когда вы завершаете продолжительный отдых то вы можете, заменить этот заговор 
          на другой из списка заклинаний волшебника.
        third_lvl: заклинание Обнаружение магии
        fifth_lvl: заклинание Туманный Шаг

      drow:
        name:
          ru: дроу
        description: |
          Дроу обычно обитают в Подземье и были им изменены. Некоторые дроу, как отдельные индивиды, так и целые 
          сообщества, избегают Подземья,но всё же сохраняют его магию. Например, в сеттинге Эберрон дроу живут в 
          тропических лесах и циклопических руинах на континенте Ксен’дрик.

        first_lvl: Дальность вашего тёмного зрения увеличивается до 120 футов. Вы также знаете заговор Пляшущие огоньки.
        third_lvl: заклинание Огонь Фей
        fifth_lvl: заклинание Тьма