RACES:
  human:
    description: | 
      Встречающиеся по всей мультивселенной, люди столь же разнообразны, сколь многочисленны, и они стремятся достичь
      как можно большего за отведенные им годы. Их амбиции и изобретательность вызывают восхищение, уважение и страх во
      многих мирах.Люди разнообразны внешне, как и жители Земли, и у них множество богов. Ученые спорят о происхождении 
      человечества, но одно из самых ранних известных скоплений людей, как говорят, произошло в Сигиле — торообразном 
      городе в центре мультивселенной, месте, где родился Общий язык. Оттуда люди могли распространиться по всем уголкам
      мультивселенной, неся с собой космополитизм Города Дверей.

    creature_type: humanoid
    size: medium
    speed: 30
    age: 100
    ideology: any
    languages: Common, +1

    race_ability:
      increase_chars: All +1

      alternative:
        increase_chars: 2 of any +1
        skills: +1
        feats: +1



  half_orc:
    description: |
      Орки связывают свое происхождение с Груумшем, могущественным богом, который бродил побескрайним просторам 
      Материального Плана. Груумш наделил своих детей дарами, чтобы они могли путешествовать по огромным равнинам,
      обширным пещерам и бурным морям и проти-востоять монстрам, скрывающимся там. Дажекогда орки начинают поклонятся 
      другим богам,они сохраняют дары Груумша: выносливость, решимость и способность видеть в темноте. В среднем орки 
      высокие и широкоплечие. У них серая кожа, заостренные уши и выдающиеся нижние клыки, похожие на маленькие бивни. 
      Молодым оркам в некоторых мирах рассказывают истории о великих путешествиях и испытаниях их предков. 
      Вдохновленные этими историями,многие орки задаются вопросом, когда Груумш призовет их совершить героические 
      подвиги древности и окажутся ли они достойны его благо-склонности. Другие орки предпочитают оставить старые 
      истории в прошлом и найти свой собственный путь.

    creature_type: humanoid
    size: medium
    speed: 30
    age: 75
    ideology: chaotic, evil
    languages: Common, Orcish

    race_ability:
      increase_chars: Strange +2, Constitution +1
      dark_vision: 60
      skills: Intimidation
      relentless_endurance: | 
        Если ваши хиты опустились до нуля, но вы при этом не убиты, ваши хиты вместо этого опускаются до 1. 
        Вы не можете использовать эту способность снова, пока не завершите длительный отдых
      savage_attacks: Если вы совершили критическое попадание рукопашной атакой оружием, вы можете добавить к урону ещё 
        одну кость урона оружия.


  elf:
    description: |
      Созданные богом Кореллоном, первые эльфы могли менять свои формы по своему желанию. Они утратили эту способность, 
      когда Кореллон проклял их за сговор с божеством Лолс, которая пыталась, но не смогла узурпировать власть Кореллона. 
      Когда Лолс была низвергнута в Бездну, большинство эльфов отвергли её и заслужили прощение Кореллона, но то, что 
      Кореллон у них отнял, было утрачено навсегда. Потеряв способность изменять форму по своему желанию, эльфы 
      отступили в Страну Фей, где их печаль только усилилась под влиянием этого плана. Со временем любопытство привело 
      многих из них к исследованию других измерений, включая миры Материального Плана. Эльфы обладают заостренными ушами 
      и не имеют растительности на лице и теле. Они живут около 750 лет и не спят, а вместо этого входят в транс, когда 
      нуждаются в отдыхе. В этом состоянии они остаются осведомлёнными о своём окружении, погружаясь в воспоминания и 
      медитации. Окружающая среда постепенно трансформирует эльфов, если они живут в ней более тысячи лет, и наделяет их 
      определённой магией. Дроу,высшие эльфы и лесные эльфы — примеры эльфов, подвергшихся таким изменениям.

    creature_type: humanoid
    size: medium
    speed: 30
    age: 750
    ideology: good chaotic, good
    languages: Common, Elvish

    race_ability:
      increase_chars: Dexterity +2
      dark_vision: 60
      skills: Perception
      fey_origin: Вы совершаете с преимуществом спасброски от очарования, и вас невозможно магически усыпить.
      trance: Эльфы не спят. Вместо этого они погружаются в глубокую медитацию, находясь в полу бессознательном состоянии 
        до 4 часов в сутки

    sub_races:
      high_elf:
        description: |
          Высшие эльфы пропитаны магией пересечения между Страной Фей и Материальным Планом. В некоторых мирах высшие 
          эльфы называют себя другими именами. Например, в сеттинге Забытых Королевств они называют себя солнечными
          или лунными эльфами, в сеттинге Драконье копьё — Сильванести и Квалинести, а в сеттинге Эберрон — Аэрени.

        increase_chars: Intelligence +1
        weapon_mastery: long_sword, short_sword, long_bow, short_bow
        cantrip: +1 from Wizard list [Intelligence]
        languages: +1 any


      dark_elf:
        description: |
          Дроу обычно обитают в Подземье и были им изменены. Некоторые дроу, как отдельные индивиды, так и целые
          сообщества, избегают Подземья,но всё же сохраняют его магию. Например, в сеттинге Эберрон дроу живут в
          тропических лесах и циклопических руинах на континенте Ксен’дрик.

        increase_chars: Charisma +1
        ideology: neutral, chaotic
        dark_vision: 120
        cantrip: +1 from Wizard list [Intelligence]
        languages: +1 any
        sun_sense: Вы совершаете с помехой броски атаки и проверки Мудрости (Внимательность), основанные на зрении, 
          если вы, цель вашей атаки или изучаемый предмет расположены на прямом солнечном свете.
        weapon_mastery: rapier, short_sword, hand_crossbow
        1_lvl: spell Dancing lights, Charisma
        3_lvl: spell Faerie fire, 1/day, Charisma
        5_lvl: spell Darkness], 1/day, Charisma