"""Создание, сохранение и загрузка персонажей.

Фасад: re-export публичного API из подмодулей для обратной совместимости.
"""

from core.abilities import ability_ids, skill_ids
from core.character_storage import (
    delete_all_characters,
    delete_character,
    load_characters,
    save_character,
    starting_max_hp,
    update_character,
)
from core.classes import load_class_full, load_classes, load_subclasses
from core.expertise import (
    expertise_step_required,
    get_expertise_grants,
)
from core.proficiencies import (
    build_fixed_proficiencies,
    get_proficiency_choices,
    has_armor_proficiency,
    has_tool_proficiency,
    has_weapon_proficiency,
    merge_proficiency_tokens,
)
from core.races import (
    build_bonuses_from_choices,
    get_choice_ability_bonus_mechanics,
    get_effective_race_bonuses,
    get_race_bonuses,
    has_choice_ability_bonuses,
    load_race_full,
    load_races,
)
from core.skills import (
    PHB_SKILL_IDS,
    apply_racial_proficiencies,
    available_skills,
    get_class_skill_config,
)
from core.stats import (
    ABILITY_SCORE_MAX,
    POINT_BUY_BUDGET,
    POINT_BUY_COSTS,
    POINT_BUY_MAX,
    POINT_BUY_MIN,
    STANDARD_ARRAY,
    STANDARD_ARRAY_MAX,
    STANDARD_ARRAY_MIN,
    STAT_NAMES,
    apply_bonuses_to_stats,
    apply_racial_bonuses_to_stats,
    can_assign_point_buy_value,
    generate_stats_point_buy,
    generate_stats_random,
    generate_stats_standard_array,
    point_buy_points_remaining,
    point_buy_total_cost,
    remaining_standard_array_pool,
    validate_final_stats,
    validate_point_buy_finish,
)

__all__ = [
    "ABILITY_SCORE_MAX",
    "POINT_BUY_BUDGET",
    "POINT_BUY_COSTS",
    "POINT_BUY_MAX",
    "POINT_BUY_MIN",
    "STANDARD_ARRAY",
    "STANDARD_ARRAY_MAX",
    "STANDARD_ARRAY_MIN",
    "STAT_NAMES",
    "apply_bonuses_to_stats",
    "apply_racial_bonuses_to_stats",
    "build_bonuses_from_choices",
    "can_assign_point_buy_value",
    "delete_all_characters",
    "delete_character",
    "generate_stats_point_buy",
    "generate_stats_random",
    "generate_stats_standard_array",
    "get_choice_ability_bonus_mechanics",
    "expertise_step_required",
    "get_class_skill_config",
    "get_expertise_grants",
    "apply_racial_proficiencies",
    "available_skills",
    "ability_ids",
    "build_fixed_proficiencies",
    "get_proficiency_choices",
    "has_armor_proficiency",
    "has_tool_proficiency",
    "has_weapon_proficiency",
    "merge_proficiency_tokens",
    "PHB_SKILL_IDS",
    "skill_ids",
    "get_effective_race_bonuses",
    "get_race_bonuses",
    "has_choice_ability_bonuses",
    "load_characters",
    "load_class_full",
    "load_classes",
    "load_subclasses",
    "load_race_full",
    "load_races",
    "point_buy_points_remaining",
    "point_buy_total_cost",
    "remaining_standard_array_pool",
    "save_character",
    "starting_max_hp",
    "update_character",
    "validate_final_stats",
    "validate_point_buy_finish",
]
