"""Прогрессия персонажа — фасад публичного API.

Реализация: xp_levels, progression_hp, asi, class_progression,
level_up_resolve; expertise — из core.expertise.
"""

from core.asi import (
    apply_asi_one_two,
    apply_asi_two_one,
    auto_asi_bonus,
    cap_stats,
    class_grants_asi_at_level,
    con_hp_bonus_from_asi,
    feat_id_from_asi_choice,
    pending_asi_at_level,
)
from core.class_progression import (
    class_features_applied_at_creation,
    features_up_to_level,
    mark_class_features_applied,
    needs_class_feature_picks,
    needs_subclass_npc,
    start_level_for_difficulty,
    subclass_is_active,
    subclass_offered_at_creation,
    subclass_skill_picks_pending,
)
from core.dice import roll
from core.expertise import (
    ExpertiseAlternative,
    ExpertiseGrant,
    default_rogue_tool_expertise,
    expertise_step_required,
    get_expertise_grants,
    grant_expertise_satisfied,
    pending_expertise_grants,
    validate_expertise_selection,
)
from core.hp_bonus import (
    HpBonusSource,
    hit_point_bonus_amount,
    hit_point_bonus_sources_from_grants,
)
from core.level_up_resolve import (
    AsiResolution,
    apply_experience,
    apply_level_up,
    apply_progression_grants_at_level,
    process_pending_level_ups,
    resolve_pending_level_ups,
)
from core.progression_hp import (
    HpGainBreakdown,
    extra_hp_bonus_sources,
    extra_hp_per_level,
    hp_gain_breakdown_for_level_up,
    hp_gain_for_level,
    max_hp_for_level,
    roll_hp_gain_for_level_up,
)
from core.xp_levels import (
    ASI_FEATURE_ID,
    EASY_START_LEVEL,
    XP_THRESHOLDS,
    grant_experience,
    has_pending_level_up,
    level_from_xp,
    xp_covers_level,
    xp_for_level,
)

__all__ = [
    "XP_THRESHOLDS",
    "level_from_xp",
    "xp_for_level",
    "xp_covers_level",
    "grant_experience",
    "has_pending_level_up",
    "HpBonusSource",
    "hit_point_bonus_amount",
    "hit_point_bonus_sources_from_grants",
    "extra_hp_bonus_sources",
    "extra_hp_per_level",
    "HpGainBreakdown",
    "hp_gain_for_level",
    "hp_gain_breakdown_for_level_up",
    "roll_hp_gain_for_level_up",
    "max_hp_for_level",
    "ASI_FEATURE_ID",
    "feat_id_from_asi_choice",
    "class_grants_asi_at_level",
    "pending_asi_at_level",
    "apply_asi_two_one",
    "apply_asi_one_two",
    "cap_stats",
    "con_hp_bonus_from_asi",
    "auto_asi_bonus",
    "ExpertiseAlternative",
    "ExpertiseGrant",
    "get_expertise_grants",
    "expertise_step_required",
    "grant_expertise_satisfied",
    "pending_expertise_grants",
    "validate_expertise_selection",
    "default_rogue_tool_expertise",
    "EASY_START_LEVEL",
    "features_up_to_level",
    "start_level_for_difficulty",
    "subclass_offered_at_creation",
    "subclass_is_active",
    "needs_subclass_npc",
    "class_features_applied_at_creation",
    "needs_class_feature_picks",
    "subclass_skill_picks_pending",
    "mark_class_features_applied",
    "apply_level_up",
    "apply_progression_grants_at_level",
    "AsiResolution",
    "process_pending_level_ups",
    "resolve_pending_level_ups",
    "apply_experience",
    "roll",
]
