default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: test_user
  password: test_password

development:
  <<: *default
  database: dnd_dev

test:
  <<: *default

production:
  <<: *default
